In [1]:
from scipy.io import loadmat, savemat
import os
import numpy as np
from tqdm import tqdm
import pandas as pd

In [2]:
rows=['p01','p02','p03','p04','p05','p06','p07','p08','p09','p10','p11','p12','p13','p14','p15','p16','p17','p18','p19','p20','p21','p22','p23','p24','p25','p26','p27','p28','p29','p30','p31','p32','p33','p34','p35','p36','p37','p38','p39','p40']

In [3]:
path = './flow/Stat_20240531_BL_180_10_01'
mat_files = [f for f in os.listdir(path) if f.endswith('.mat')]
means = np.empty((40,21))
rio = np.empty((3,21))
i=0
for f in tqdm((mat_files)):
    if (0.0<= float(f[-10:-4]) <= 180) and f.startswith('Stat_20240531_BL_180_10_01_cDAQ'):
        filepath = path + '/' +f
        f1 = loadmat(filepath)

        for j,(keys,values) in enumerate(f1.items()):
            if keys.startswith('cDAQ') and j<40:
                print(values, np.max(values), np.min(values), np.mean(values))
                means[j,i]=np.median(values)
    if (0.0<= float(f[-10:-4]) <= 180) and f.startswith('Stat_20240531_BL_180_10_01_RIO'):
        filepath = path + '/' +f
        f1 = loadmat(filepath)
        k=0
        for keys,values in f1.items():
            if keys.startswith('AI00'):
                rio[k,i]=np.mean(values)
                k+=1
            if keys.startswith('Dens') or keys.startswith('Sam'):
                rio[k,i]=float(values)
                k+=1
                if k==3:
                    break
        i+=1

        

 13%|███████████                                                                       | 11/82 [00:00<00:01, 36.98it/s]

[[0.6497079 ]
 [0.64587414]
 [0.64140135]
 ...
 [0.62574667]
 [0.6314974 ]
 [0.62894154]] 0.74076056 0.6078557 0.67614204
[[-0.56479275]
 [-0.5593612 ]
 [-0.5615977 ]
 ...
 [-0.53028643]
 [-0.5258134 ]
 [-0.5270914 ]] -0.45712024 -0.62933236 -0.537052
[[-0.94210786]
 [-0.94370544]
 [-0.9417884 ]
 ...
 [-0.9187834 ]
 [-0.9149493 ]
 [-0.9101566 ]] -0.84114176 -1.0053715 -0.9199005
[[-1.0704181]
 [-1.0710574]
 [-1.0707378]
 ...
 [-1.0362203]
 [-1.0352615]
 [-1.0343027]] -0.9802893 -1.1167611 -1.0450634
[[-1.0693371]
 [-1.0651834]
 [-1.0651834]
 ...
 [-1.0354688]
 [-1.0329127]
 [-1.0313151]] -0.9856249 -1.1143882 -1.0478615
[[-1.582372 ]
 [-1.5801355]
 [-1.5753429]
 ...
 [-1.5286953]
 [-1.5341269]
 [-1.5370024]] -1.460002 -1.6485093 -1.554074
[[-1.0167389]
 [-1.0199335]
 [-1.0192945]
 ...
 [-0.9918216]
 [-0.9835158]
 [-0.9831964]] -0.9410286 -1.0589067 -0.99779725
[[-0.98649   ]
 [-0.983296  ]
 [-0.98201835]
 ...
 [-0.96796453]
 [-0.9558271 ]
 [-0.95550776]] -0.9114298 -1.0302485 -0.967852

 18%|███████████████                                                                   | 15/82 [00:01<00:07,  8.80it/s]

[[0.9592869 ]
 [0.9624818 ]
 [0.96152335]
 ...
 [0.99666643]
 [0.9982639 ]
 [0.9998613 ]] 1.0621605 0.93117243 0.9967759
[[-1.5693102]
 [-1.5686712]
 [-1.5683517]
 ...
 [-1.5156337]
 [-1.5137167]
 [-1.5140362]] -1.4223388 -1.660688 -1.5409132
[[-1.6418414]
 [-1.6344925]
 [-1.632895 ]
 ...
 [-1.5852876]
 [-1.585607 ]
 [-1.5865656]] -1.5092435 -1.7185245 -1.6091945
[[-1.5776329]
 [-1.5773133]
 [-1.5747564]
 ...
 [-1.5268155]
 [-1.5268155]
 [-1.5226606]] -1.4581002 -1.6428325 -1.5498881
[[-1.4732002]
 [-1.4744782]
 [-1.4725612]
 ...
 [-1.4342197]
 [-1.4329417]
 [-1.4294271]] -1.3703173 -1.5409368 -1.4530039
[[-2.1284044]
 [-2.1274457]
 [-2.1268067]
 ...
 [-2.056516 ]
 [-2.057155 ]
 [-2.059711 ]] -1.9660963 -2.2060437 -2.0885446
[[-1.3083996]
 [-1.3074411]
 [-1.3071218]
 ...
 [-1.264954 ]
 [-1.2655928]
 [-1.2668706]] -1.2167165 -1.3668594 -1.2881186
[[-1.2381811]
 [-1.2369035]
 [-1.2381811]
 ...
 [-1.1972973]
 [-1.1957003]
 [-1.196978 ]] -1.1426791 -1.2966323 -1.2166239
[[-1.1788447]
 [-1.

 21%|█████████████████                                                                 | 17/82 [00:01<00:09,  6.96it/s]

[[1.1151947]
 [1.108805 ]
 [1.1040127]
 ...
 [1.1318078]
 [1.1311688]
 [1.1305299]] 1.2145538 1.0870801 1.1529888
[[-2.1162994]
 [-2.1178968]
 [-2.1143823]
 ...
 [-2.136428 ]
 [-2.133233 ]
 [-2.1335526]] -1.9680499 -2.245059 -2.102917
[[-2.0006545]
 [-2.000335 ]
 [-2.002891 ]
 ...
 [-2.0032105]
 [-1.9980984]
 [-2.0006545]] -1.8619858 -2.089479 -1.9725893
[[-1.8272452]
 [-1.8272452]
 [-1.8272452]
 ...
 [-1.8266059]
 [-1.828204 ]
 [-1.8269256]] -1.7048361 -1.8934036 -1.7977825
[[-1.6738538]
 [-1.6719368]
 [-1.6709782]
 ...
 [-1.6767294]
 [-1.6741732]
 [-1.6754513]] -1.5591489 -1.7345611 -1.645282
[[-2.3948708]
 [-2.393912 ]
 [-2.3923147]
 ...
 [-2.393912 ]
 [-2.3919952]
 [-2.393912 ]] -2.2165873 -2.4789002 -2.3491032
[[-1.4735568]
 [-1.4764318]
 [-1.4757929]
 ...
 [-1.4668483]
 [-1.4674871]
 [-1.4671676]] -1.3659011 -1.5240303 -1.4434294
[[-1.393412 ]
 [-1.3924538]
 [-1.3940508]
 ...
 [-1.3911761]
 [-1.3921344]
 [-1.391815 ]] -1.2864113 -1.4521825 -1.3684083
[[-1.3287235]
 [-1.3312801]
 

 23%|███████████████████                                                               | 19/82 [00:02<00:10,  5.80it/s]

[[1.3506536]
 [1.3506536]
 [1.3487368]
 ...
 [1.3813239]
 [1.3746148]
 [1.3746148]] 1.4075216 1.2695049 1.3432677
[[-2.5885248]
 [-2.5859687]
 [-2.5875664]
 ...
 [-2.624309 ]
 [-2.624309 ]
 [-2.6223922]] -2.4409144 -2.8284714 -2.6406069
[[-2.2575428]
 [-2.249555 ]
 [-2.2489161]
 ...
 [-2.2930088]
 [-2.2965236]
 [-2.2930088]] -2.1533816 -2.444458 -2.3028884
[[-1.9570053]
 [-1.9554071]
 [-1.9563661]
 ...
 [-1.9956776]
 [-1.9966364]
 [-1.9912031]] -1.8879703 -2.1164887 -2.0040154
[[-1.7716244]
 [-1.7751391]
 [-1.7767366]
 ...
 [-1.8029367]
 [-1.8051732]
 [-1.8038951]] -1.7048464 -1.9259487 -1.8151337
[[-2.5958385]
 [-2.5951996]
 [-2.5958385]
 ...
 [-2.6389718]
 [-2.6434448]
 [-2.6402497]] -2.4734685 -2.828757 -2.6503425
[[-1.6454225]
 [-1.6463808]
 [-1.6460613]
 ...
 [-1.6751316]
 [-1.6767288]
 [-1.6764094]] -1.5594896 -1.8070656 -1.6797514
[[-1.59847  ]
 [-1.5959147]
 [-1.5975118]
 ...
 [-1.6374375]
 [-1.6396732]
 [-1.637118 ]] -1.5144665 -1.766477 -1.6342064
[[-1.3788961]
 [-1.396153 ]


 24%|████████████████████                                                              | 20/82 [00:02<00:11,  5.46it/s]

[[1.4228568]
 [1.419662 ]
 [1.4193425]
 ...
 [1.4624727]
 [1.4605558]
 [1.4640701]] 1.5730138 1.398576 1.4923184
[[-2.8805506]
 [-2.8732018]
 [-2.8747995]
 ...
 [-2.8981233]
 [-2.8978038]
 [-2.8946087]] -2.6380477 -3.0831153 -2.8781576
[[-2.4431798]
 [-2.4364703]
 [-2.4329555]
 ...
 [-2.453085 ]
 [-2.455641 ]
 [-2.4521263]] -2.2610576 -2.6007 -2.4404716
[[-2.0915594]
 [-2.0906005]
 [-2.0941162]
 ...
 [-2.1081789]
 [-2.1100965]
 [-2.108818 ]] -1.933674 -2.2283506 -2.0953007
[[-1.9214755]
 [-1.919239 ]
 [-1.9208366]
 ...
 [-1.934895 ]
 [-1.934895 ]
 [-1.934895 ]] -1.7566074 -2.0722852 -1.9202055
[[-2.8524003]
 [-2.8341887]
 [-2.8517613]
 ...
 [-2.8779607]
 [-2.8763633]
 [-2.8728485]] -2.5897682 -3.0926673 -2.8555152
[[-1.825594 ]
 [-1.8300663]
 [-1.8252745]
 ...
 [-1.8412471]
 [-1.8338997]
 [-1.8323025]] -1.6629924 -1.985001 -1.8275006
[[-1.5639743]
 [-1.5757922]
 [-1.5588638]
 ...
 [-1.6677809]
 [-1.6882228]
 [-1.672572 ]] -1.1921868 -1.8600627 -1.613305
[[-1.1615878]
 [-1.1651032]
 [-1

 26%|█████████████████████                                                             | 21/82 [00:03<00:11,  5.09it/s]

[[1.7778023]
 [1.7774829]
 [1.7784413]
 ...
 [1.8522419]
 [1.8570342]
 [1.8551173]] 1.8877045 1.7059187 1.7856947
[[-2.9930155]
 [-2.9917376]
 [-2.99014  ]
 ...
 [-3.1495721]
 [-3.1511695]
 [-3.15085  ]] -2.8572268 -3.2738588 -3.0649028
[[-2.4780068]
 [-2.479285 ]
 [-2.4853556]
 ...
 [-2.594629 ]
 [-2.5949485]
 [-2.606451 ]] -2.3811944 -2.7243514 -2.5429544
[[-2.1615531]
 [-2.1554806]
 [-2.1577177]
 ...
 [-2.3226345]
 [-2.3200777]
 [-2.3207169]] -2.0474536 -2.4418476 -2.215914
[[-2.015412 ]
 [-2.0080633]
 [-2.010939 ]
 ...
 [-2.2470584]
 [-2.2435436]
 [-2.2416265]] -1.8984708 -2.3895607 -2.082222
[[-3.0137498]
 [-3.0140693]
 [-3.0108743]
 ...
 [-3.1223812]
 [-3.138037 ]
 [-3.1536927]] -2.4044557 -3.7026005 -3.111086
[[-1.4607786]
 [-1.4668483]
 [-1.457584 ]
 ...
 [-1.4952796]
 [-1.4895294]
 [-1.4876126]] -1.1333393 -2.0121546 -1.4939708
[[-1.2416946]
 [-1.2547902]
 [-1.2701217]
 ...
 [-1.3812746]
 [-1.3851075]
 [-1.3812746]] -1.0839086 -1.5058426 -1.3131725
[[-1.2411611]
 [-1.2501091]


 27%|██████████████████████                                                            | 22/82 [00:03<00:12,  4.87it/s]

[[1.6647054]
 [1.6647054]
 [1.6685392]
 ...
 [1.5097562]
 [1.5107147]
 [1.5119926]] 1.6746094 1.400493 1.4921547
[[-2.8463638]
 [-2.8444467]
 [-2.8479612]
 ...
 [-2.9086668]
 [-2.9067497]
 [-2.9070692]] -2.6450768 -3.0380654 -2.871078
[[-2.3997262]
 [-2.396531 ]
 [-2.39717  ]
 ...
 [-2.4623508]
 [-2.4636288]
 [-2.4629898]] -2.2604184 -2.5633168 -2.4263027
[[-2.0589595]
 [-2.057042 ]
 [-2.0615163]
 ...
 [-2.114571 ]
 [-2.1136122]
 [-2.1142514]] -1.9387877 -2.197988 -2.08274
[[-1.8933585]
 [-1.8933585]
 [-1.894317 ]
 ...
 [-1.9387292]
 [-1.9374511]
 [-1.9390488]] -1.7649148 -2.028512 -1.9137135
[[-2.825562 ]
 [-2.8297155]
 [-2.8377032]
 ...
 [-2.8929775]
 [-2.890102 ]
 [-2.8885043]] -2.606063 -3.0322812 -2.851453
[[-1.8073851]
 [-1.8144131]
 [-1.8176076]
 ...
 [-1.8549836]
 [-1.8482751]
 [-1.852428 ]] -1.6677841 -1.9514585 -1.8254665
[[-1.3739283]
 [-1.3940508]
 [-1.3994807]
 ...
 [-1.482526 ]
 [-1.514147 ]
 [-1.5023291]] -1.1206402 -1.8159848 -1.4995515
[[-1.1612684]
 [-1.171175 ]
 [-1.

 29%|████████████████████████                                                          | 24/82 [00:03<00:13,  4.23it/s]

[[1.1861199]
 [1.1794107]
 [1.1810081]
 ...
 [1.1241401]
 [1.1193479]
 [1.1142362]] 1.2084837 1.043311 1.1137518
[[-2.3655117]
 [-2.3635948]
 [-2.3613582]
 ...
 [-2.4028935]
 [-2.4016156]
 [-2.400657 ]] -2.146013 -2.4968274 -2.3510845
[[-2.109928 ]
 [-2.109928 ]
 [-2.1137621]
 ...
 [-2.1469915]
 [-2.1524231]
 [-2.14795  ]] -1.9578397 -2.224633 -2.107708
[[-1.8595254]
 [-1.8608038]
 [-1.8592058]
 ...
 [-1.9058683]
 [-1.9045899]
 [-1.9039506]] -1.752777 -1.9566857 -1.8655827
[[-1.6799245]
 [-1.680244 ]
 [-1.6770489]
 ...
 [-1.7240171]
 [-1.7249757]
 [-1.7249757]] -1.586627 -1.7716244 -1.6897478
[[-2.4316137]
 [-2.430655 ]
 [-2.4325721]
 ...
 [-2.4888048]
 [-2.4897633]
 [-2.4894438]] -2.2616374 -2.5654857 -2.433501
[[-1.5320166]
 [-1.5304193]
 [-1.5323361]
 ...
 [-1.5607674]
 [-1.5630035]
 [-1.5598091]] -1.4096661 -1.6224219 -1.5252014
[[-1.4847618]
 [-1.4831648]
 [-1.4847618]
 ...
 [-1.509356 ]
 [-1.5087172]
 [-1.5083978]] -1.3515699 -1.5853744 -1.4755789
[[-1.4444082]
 [-1.4460061]
 [-1

 30%|█████████████████████████                                                         | 25/82 [00:04<00:14,  4.02it/s]

[[1.0497006]
 [1.0532149]
 [1.0490617]
 ...
 [0.9995418]
 [1.0059315]
 [1.0046536]] 1.0758983 0.9219074 0.9969283
[[-2.1456935]
 [-2.1469717]
 [-2.1444156]
 ...
 [-2.0437722]
 [-2.0434527]
 [-2.0428135]] -1.9587843 -2.2536857 -2.0938978
[[-2.00353  ]
 [-2.0038495]
 [-2.0000155]
 ...
 [-1.9028835]
 [-1.9000078]
 [-1.9022444]] -1.8424956 -2.073823 -1.9504094
[[-1.8128629]
 [-1.8115845]
 [-1.8115845]
 ...
 [-1.7281673]
 [-1.7272085]
 [-1.7284869]] -1.6818244 -1.8739077 -1.768774
[[-1.6572392]
 [-1.6562806]
 [-1.6575587]
 ...
 [-1.5760831]
 [-1.5764027]
 [-1.5773611]] -1.531032 -1.7102782 -1.6151769
[[-2.3651567]
 [-2.3638787]
 [-2.3641982]
 ...
 [-2.2501354]
 [-2.2485378]
 [-2.2463012]] -2.180803 -2.4456718 -2.3061562
[[-1.4642925]
 [-1.4620564]
 [-1.4633342]
 ...
 [-1.3825126]
 [-1.3812348]
 [-1.3831515]] -1.342581 -1.5086966 -1.4204725
[[-1.3863851]
 [-1.3857462]
 [-1.3854269]
 ...
 [-1.3132414]
 [-1.311325 ]
 [-1.3122832]] -1.270441 -1.442281 -1.3506513
[[-1.3347954]
 [-1.3354346]
 [-1

 32%|██████████████████████████                                                        | 26/82 [00:04<00:14,  3.79it/s]

[[0.9266997 ]
 [0.93276983]
 [0.93372834]
 ...
 [0.88388896]
 [0.8845279 ]
 [0.8835695 ]] 0.9564116 0.8305353 0.89268625
[[-1.7846552]
 [-1.7872113]
 [-1.7856138]
 ...
 [-1.8597385]
 [-1.8606969]
 [-1.861336 ]] -1.6999869 -1.9619794 -1.8334568
[[-1.7252343]
 [-1.731305 ]
 [-1.7370563]
 ...
 [-1.8201296]
 [-1.8182125]
 [-1.8230052]] -1.6763488 -1.9009664 -1.7847066
[[-1.6086347]
 [-1.6105523]
 [-1.6121503]
 ...
 [-1.7013204]
 [-1.7006812]
 [-1.700042 ]] -1.568684 -1.7569319 -1.6596754
[[-1.4875783]
 [-1.4910929]
 [-1.492371 ]
 ...
 [-1.5783197]
 [-1.5780002]
 [-1.5773611]] -1.4505149 -1.6217734 -1.5325555
[[-2.1216948]
 [-2.1213753]
 [-2.1236117]
 ...
 [-2.2526913]
 [-2.2501354]
 [-2.2488573]] -2.0581133 -2.3191483 -2.190621
[[-1.3007326]
 [-1.2997743]
 [-1.3007326]
 ...
 [-1.383471 ]
 [-1.3812348]
 [-1.383471 ]] -1.2710235 -1.4262776 -1.3446304
[[-1.2276407]
 [-1.227002 ]
 [-1.2257243]
 ...
 [-1.3036592]
 [-1.3036592]
 [-1.305895 ]] -1.1950614 -1.3525281 -1.2677175
[[-1.1660619]
 [-1.1

 33%|███████████████████████████                                                       | 27/82 [00:04<00:14,  3.78it/s]

[[0.77494526]
 [0.7746258 ]
 [0.7679166 ]
 ...
 [0.7592906 ]
 [0.75481784]
 [0.75194246]] 0.8586498 0.71456295 0.7866555
[[-1.5284138]
 [-1.5277748]
 [-1.5258578]
 ...
 [-1.53736  ]
 [-1.5367209]
 [-1.5395964]] -1.4731398 -1.6798582 -1.569577
[[-1.5741045]
 [-1.5808144]
 [-1.5833704]
 ...
 [-1.5971096]
 [-1.596151 ]
 [-1.6012632]] -1.523941 -1.7095782 -1.6152394
[[-1.5076392]
 [-1.5082784]
 [-1.5114745]
 ...
 [-1.5335273]
 [-1.5322489]
 [-1.5300117]] -1.4683276 -1.624615 -1.5442611
[[-1.4140905]
 [-1.4128125]
 [-1.4099369]
 ...
 [-1.4316636]
 [-1.4300661]
 [-1.4313442]] -1.372554 -1.5179319 -1.4431711
[[-2.0252044]
 [-2.0264826]
 [-2.0252044]
 ...
 [-2.060989 ]
 [-2.0584328]
 [-2.0574744]] -1.9581087 -2.1792054 -2.0714943
[[-1.2493007]
 [-1.2515368]
 [-1.2524953]
 ...
 [-1.2719818]
 [-1.2726208]
 [-1.2729403]] -1.2151192 -1.3432199 -1.2763044
[[-1.1810076]
 [-1.1813271]
 [-1.1819658]
 ...
 [-1.1966585]
 [-1.1972973]
 [-1.200172 ]] -1.1417209 -1.2713993 -1.2044963
[[-1.116848 ]
 [-1.118

 34%|████████████████████████████                                                      | 28/82 [00:04<00:14,  3.70it/s]

[[0.723189  ]
 [0.7273423 ]
 [0.7219111 ]
 ...
 [0.68517053]
 [0.68293417]
 [0.68453157]] 0.7541789 0.59603477 0.6682785
[[-1.2942181]
 [-1.2932596]
 [-1.2958156]
 ...
 [-1.3069983]
 [-1.3082763]
 [-1.3050812]] -1.1852676 -1.3990151 -1.2967056
[[-1.4277676]
 [-1.422975 ]
 [-1.4268091]
 ...
 [-1.4526896]
 [-1.4456604]
 [-1.4450214]] -1.3363869 -1.5236216 -1.4322782
[[-1.4060044]
 [-1.4085613]
 [-1.4066436]
 ...
 [-1.4334906]
 [-1.433171 ]
 [-1.4322121]] -1.3289794 -1.4897412 -1.412828
[[-1.3326149]
 [-1.3322954]
 [-1.3322954]
 ...
 [-1.3553003]
 [-1.3540223]
 [-1.3546613]] -1.2588077 -1.4086589 -1.3380363
[[-1.9159341]
 [-1.9184902]
 [-1.9178512]
 ...
 [-1.9565111]
 [-1.9584281]
 [-1.9565111]] -1.8057053 -2.031914 -1.9313258
[[-1.1924381]
 [-1.1898824]
 [-1.1889241]
 ...
 [-1.2186332]
 [-1.2167165]
 [-1.2151192]] -1.1282281 -1.2671901 -1.1985669
[[-1.1302223]
 [-1.129264 ]
 [-1.12607  ]
 ...
 [-1.1519418]
 [-1.1529   ]
 [-1.1516224]] -1.0704936 -1.2027272 -1.135972
[[-1.0772212]
 [-1.07

 35%|█████████████████████████████                                                     | 29/82 [00:05<00:13,  3.85it/s]

[[0.6171207 ]
 [0.610731  ]
 [0.5950763 ]
 ...
 [0.5503487 ]
 [0.5487513 ]
 [0.55258507]] 0.63660914 0.49284178 0.55828005
[[-1.0296696]
 [-1.0296696]
 [-1.0229601]
 ...
 [-1.0213625]
 [-1.0181675]
 [-1.017209 ]] -0.92774814 -1.1341472 -1.041799
[[-1.252355 ]
 [-1.251716 ]
 [-1.2571477]
 ...
 [-1.2494794]
 [-1.2533135]
 [-1.2600234]] -1.1692816 -1.3408601 -1.2618731
[[-1.2874306]
 [-1.287111 ]
 [-1.2864718]
 ...
 [-1.2893482]
 [-1.2915856]
 [-1.2941424]] -1.210086 -1.3647753 -1.2907335
[[-1.2351638]
 [-1.2364419]
 [-1.2358028]
 ...
 [-1.2460272]
 [-1.2409151]
 [-1.2399565]] -1.1667882 -1.3137637 -1.2411315
[[-1.8002737]
 [-1.7970786]
 [-1.8015517]
 ...
 [-1.8114563]
 [-1.8104979]
 [-1.8098588]] -1.6926008 -1.9073075 -1.8041197
[[-1.1266308]
 [-1.1266308]
 [-1.1342976]
 ...
 [-1.1336588]
 [-1.1333393]
 [-1.1358949]] -1.064018 -1.189563 -1.1297016
[[-1.0800757]
 [-1.0813533]
 [-1.0848668]
 ...
 [-1.0826309]
 [-1.0816727]
 [-1.0832697]] -1.0126812 -1.139485 -1.0773253
[[-1.0337595]
 [-1.0

 37%|██████████████████████████████                                                    | 30/82 [00:05<00:13,  3.90it/s]

[[0.5113718 ]
 [0.50466263]
 [0.5081769 ]
 ...
 [0.4548233 ]
 [0.4545038 ]
 [0.46057397]] 0.52159524 0.375911 0.44183668
[[-0.78716683]
 [-0.7855693 ]
 [-0.78588885]
 ...
 [-0.82071465]
 [-0.8223122 ]
 [-0.81943667]] -0.700262 -0.8839763 -0.7953662
[[-1.0925986]
 [-1.0983497]
 [-1.092918 ]
 ...
 [-1.0993083]
 [-1.0989888]
 [-1.1037815]] -1.0031348 -1.167045 -1.0887152
[[-1.1755686]
 [-1.169496 ]
 [-1.1675783]
 ...
 [-1.1755686]
 [-1.1742902]
 [-1.1701353]] -1.0867181 -1.2340565 -1.1608846
[[-1.1492151]
 [-1.1463394]
 [-1.1457005]
 ...
 [-1.1421858]
 [-1.1431444]
 [-1.1418663]] -1.0651834 -1.202254 -1.1355299
[[-1.6858913]
 [-1.6874888]
 [-1.6852523]
 ...
 [-1.6721526]
 [-1.6708746]
 [-1.6750281]] -1.5600067 -1.7545847 -1.6637205
[[-1.0598651]
 [-1.0636985]
 [-1.0624207]
 ...
 [-1.0598651]
 [-1.0589067]
 [-1.0621012]] -0.9918216 -1.1128943 -1.0530539
[[-1.0177917]
 [-1.023541 ]
 [-1.0238605]
 ...
 [-1.0174723]
 [-1.0145977]
 [-1.0152365]] -0.94943905 -1.075604 -1.0115167
[[-0.9784737 ]


 38%|███████████████████████████████                                                   | 31/82 [00:05<00:12,  4.00it/s]

[[0.3832591 ]
 [0.38996825]
 [0.39507997]
 ...
 [0.34268475]
 [0.3493939 ]
 [0.35035235]] 0.39923325 0.26568934 0.32839167
[[-0.5970626 ]
 [-0.59674305]
 [-0.5989796 ]
 ...
 [-0.57437783]
 [-0.57501686]
 [-0.57246083]] -0.483 -0.67917484 -0.5655058
[[-0.9497762 ]
 [-0.95392984]
 [-0.9462615 ]
 ...
 [-0.9219786 ]
 [-0.919742  ]
 [-0.9226176 ]] -0.8484906 -1.0261399 -0.92392546
[[-1.0601908]
 [-1.0630672]
 [-1.0611496]
 ...
 [-1.0272714]
 [-1.0282302]
 [-1.0311066]] -0.9700619 -1.1212355 -1.0361774
[[-1.0587932]
 [-1.0594321]
 [-1.0575151]
 ...
 [-1.0223688]
 [-1.0230079]
 [-1.0201322]] -0.973803 -1.1159859 -1.0338477
[[-1.5622432]
 [-1.5606457]
 [-1.5612847]
 ...
 [-1.5187907]
 [-1.5159152]
 [-1.5162346]] -1.4318856 -1.6449947 -1.5291102
[[-0.9946967]
 [-0.9940578]
 [-0.9940578]
 ...
 [-0.9691404]
 [-0.9707377]
 [-0.9713766]] -0.92473644 -1.049962 -0.97993624
[[-0.9660481]
 [-0.9657287]
 [-0.9638123]
 ...
 [-0.9353852]
 [-0.9337882]
 [-0.9350658]] -0.8951402 -1.0142783 -0.94888663
[[-0.

100%|██████████████████████████████████████████████████████████████████████████████████| 82/82 [00:06<00:00, 11.76it/s]


In [12]:
path = './flow/Stat_20240531_BL_180_10_01'
mat_files = [f for f in os.listdir(path) if f.endswith('.mat')]
means = np.empty((40,21))
rio = np.empty((3,21))
i = 0

for f in tqdm(mat_files):
    aoa_value = float(f[-10:-4])
    
    if 0.0 <= aoa_value <= 180:
        filepath = os.path.join(path, f)
        f1 = loadmat(filepath)
        
        if f.startswith('Stat_20240531_BL_180_10_01_cDAQ'):
            for j, (key, value) in enumerate(f1.items()):
                if key.startswith('cDAQ') and j < 40:
                    means[j, i] = np.mean(value)
        elif f.startswith('Stat_20240531_BL_180_10_01_RIO'):
            k = 0
            for key, value in f1.items():
                if key.startswith('AI00'):
                    rio[k, i] = np.mean(value)
                    k += 1
                elif key.startswith('Dens') or key.startswith('Sam'):
                    rio[k, i] = float(value)
                    k += 1
                if k == 3:
                    break
            i += 1

  0%|          | 0/82 [00:00<?, ?it/s]/var/folders/h1/gk_1qybx6sd2xjqymf15mww00000gn/T/ipykernel_11709/711516325.py:25: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  rio[k, i] = float(value)
100%|██████████| 82/82 [00:00<00:00, 457.35it/s]


In [28]:
no_flow = np.empty((40,1))
f1 = loadmat('./noflow/Stat_20240531_BL_180_10_01/Stat_20240529_BL_180_20_01_cDAQ_Group00000_Group00000_No_Movement.mat')
for j,(keys,values) in enumerate(f1.items()):
    if keys.startswith('cDAQ') and j<40:
        no_flow[j,0]=np.mean(values)

In [4]:
#means1=means-no_flow
means1=means

means_df = pd.DataFrame(means1,index=rows,columns=['AoA_' + str(i) for i in np.arange(-10, 11, 1)])

means_df.to_csv('means_df.csv')